#!/bin/bash

declare param_camera="$(find-camera C920)"
declare param_camera_rules='-z'
declare param_screen='X11:DP-3'
source "$HOME/Development/mduk/BashPlayground/advanced-argument-parser.sh"

camera="$param_camera" \
  source ./camera-options.sh

declare tmp="$(mktemp).mlt"

./scmlt \
  mode: preview \
  camera: "$param_camera" \
  screen: "$param_screen" \
  >"$tmp"

melt "$tmp"
