#!/bin/bash

declare param_camera=''
declare param_screen=''
source "$HOME/Development/mduk/BashPlayground/advanced-argument-parser.sh"

if [[ -z $param_camera ]]
then
  if find-camera C920 >/dev/null
  then declare param_camera="$(find-camera C920)"
  else declare param_camera="$(find-camera Integrated)"
  fi
fi

if [[ -z $param_screen ]]
then
  if hdmi-connected
  then declare param_screen='X11:DP-3'
  else declare param_screen='X11:eDP-1'
  fi
fi

declare tmp="$(mktemp).mlt"

./scmlt \
  mode: preview \
  camera: "$param_camera" \
  screen: "$param_screen" \
  >"$tmp"

melt "$tmp"
