#!/bin/bash

declare scfile="${1:-$SCREENCAST_DIR/latest.lnk}"

if [[ -L $scfile ]]
then scfile="$(readlink $scfile)"
fi

declare outfile="${scfile%.*}.render.mp4"
declare mltfile="${scfile%.*}.render.mlt"

if [[ -f $outfile ]]
then
  echo "ERROR: $outfile already exists." >&2
  exit 1
fi

scmlt \
  mode: render \
  scfile: "$scfile" \
  >"$mltfile"

melt "$mltfile" \
  -consumer "avformat:$outfile" \
    properties='x264-medium' \
    f=mkv \
    vcodec=libx264 \
    acodec=aac \
    g=120 \
    crf=23 \
    ab=320k
